[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vesting = "6ZwThBj53u1bW3vEbbofj6GNmTo1qDwCCg8N5Aa4RDrV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/projects/investor_vesting_contract/keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/vesting.ts\""

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false
